version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels:
      - dependencies
    assignees:
      - rdmnl
    reviewers:
      - rdmnl

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
    assignees:
      - rdmnl
    reviewers:
      - rdmnl
